#!/bin/sh
# Writes config.local.js (gitignored) from the OPENROUTER_API_KEY in your shell env,
# so the extension picks up the key without you pasting it into the settings panel.
set -e
cd "$(dirname "$0")"

if [ -z "$OPENROUTER_API_KEY" ]; then
  echo "OPENROUTER_API_KEY is not set. Export it in your shell profile, then re-run." >&2
  exit 1
fi

cat > config.local.js <<EOF
// Generated by write-local-config.sh. Gitignored: never commit this file.
self.LOCAL_OPENROUTER_API_KEY = "$OPENROUTER_API_KEY";
EOF

echo "Wrote config.local.js. Reload the extension at chrome://extensions to pick it up."
