#!/bin/sh
# Writes config.local.js (gitignored) from the provider keys in your shell env, so
# the extension picks them up without you pasting anything into the settings panel.
# Either key may be absent; only the provider you actually select needs one.
set -e
cd "$(dirname "$0")"

# GOOGLE_API_KEY is the fallback because that is what Google's own tooling exports.
GEMINI_KEY="${GEMINI_API_KEY:-$GOOGLE_API_KEY}"

if [ -z "$GEMINI_KEY" ] && [ -z "$OPENROUTER_API_KEY" ]; then
  echo "Neither GEMINI_API_KEY (or GOOGLE_API_KEY) nor OPENROUTER_API_KEY is set." >&2
  echo "Export at least one in your shell profile, then re-run." >&2
  exit 1
fi

{
  echo "// Generated by write-local-config.sh. Gitignored: never commit this file."
  [ -n "$GEMINI_KEY" ] && echo "self.LOCAL_GEMINI_API_KEY = \"$GEMINI_KEY\";"
  [ -n "$OPENROUTER_API_KEY" ] && echo "self.LOCAL_OPENROUTER_API_KEY = \"$OPENROUTER_API_KEY\";"
} > config.local.js

echo "Wrote config.local.js with:"
[ -n "$GEMINI_KEY" ] && echo "  - Gemini key"
[ -n "$OPENROUTER_API_KEY" ] && echo "  - OpenRouter key"
echo "Reload the extension at chrome://extensions to pick it up."
